# Copyright © 2023 Verizon Connect IRL Limited. All rights reserved.
#
# Module manifest for module 'conventional.commits
#
# Generated by: Verizon Connect IRL Limited
#
# Generated on: 2023/04/21
#

@{

  # Script module or binary module file associated with this manifest.
  RootModule        = 'conventional.commits.psm1'

  # Version number of this module.
  ModuleVersion     = '1.0.0'

  # ID used to uniquely identify this module
  GUID              = '5f26d86f-4223-4a74-9e24-77e66698e865'

  # Author of this module
  Author            = 'Verizon Connect'

  # Company or vendor of this module
  CompanyName       = 'Verizon Connect'

  # Copyright statement for this module
  Copyright         = '(c) 2023 Verizon Connect IRL Limited. All rights reserved.'

  # Description of the functionality provided by this module
  Description       = 'Uses conventional commits to calculate sem-ver version strings.'

  # Modules that must be imported into the global environment prior to importing this module
  RequiredModules   = @(
  )

  # Functions to export from this module
  FunctionsToExport = 'Get-*'

  # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
  PrivateData       = @{
    PSData = @{
      # Tags applied to this module. These help with module discovery in online galleries.
      Tags       = @('Continuous', 'Integration', 'Delivery', 'DevOps', 'conventional-commits', 'conventional-changelog', 'git')

      # Prerelease of this module e.g alpha
      Prerelease = ''
    } # End of PSData hashtable

  } # End of PrivateData hashtable

}
